-- MySQL Script generated by MySQL Workbench
-- jue 26 abr 2018 18:23:27 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema 4BankDB
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `4BankDB` ;

-- -----------------------------------------------------
-- Schema 4BankDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `4BankDB` DEFAULT CHARACTER SET utf8 ;
USE `4BankDB` ;

-- -----------------------------------------------------
-- Table `4BankDB`.`USER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `4BankDB`.`USER` ;

CREATE TABLE IF NOT EXISTS `4BankDB`.`USER` (
  `idUSER` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `NIF` VARCHAR(15) NOT NULL,
  `phone_number` INT NOT NULL,
  PRIMARY KEY (`idUSER`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  UNIQUE INDEX `NIF_UNIQUE` (`NIF` ASC),
  UNIQUE INDEX `phone_number_UNIQUE` (`phone_number` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `4BankDB`.`ACCOUNT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `4BankDB`.`ACCOUNT` ;

CREATE TABLE IF NOT EXISTS `4BankDB`.`ACCOUNT` (
  `idACCOUNT` INT NOT NULL,
  `idUSER` INT NOT NULL,
  `account_number` VARCHAR(10) NOT NULL,
  `balance` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idACCOUNT`),
  UNIQUE INDEX `account_number_UNIQUE` (`account_number` ASC),
  INDEX `fk_ACCOUNT_1_idx` (`idUSER` ASC),
  CONSTRAINT `fk_ACCOUNT_1`
    FOREIGN KEY (`idUSER`)
    REFERENCES `4BankDB`.`USER` (`idUSER`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `4BankDB`.`EMPLOYEE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `4BankDB`.`EMPLOYEE` ;

CREATE TABLE IF NOT EXISTS `4BankDB`.`EMPLOYEE` (
  `idUSER` INT NOT NULL,
  `isEmployee` TINYINT(1) NOT NULL,
  PRIMARY KEY (`idUSER`),
  CONSTRAINT `fk_EMPLOYEE_1`
    FOREIGN KEY (`idUSER`)
    REFERENCES `4BankDB`.`USER` (`idUSER`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `4BankDB`.`MOVEMENT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `4BankDB`.`MOVEMENT` ;

CREATE TABLE IF NOT EXISTS `4BankDB`.`MOVEMENT` (
  `idMOVEMENT` INT NOT NULL AUTO_INCREMENT,
  `idACCOUNT` INT NOT NULL,
  `idACCOUNT_receptor` INT NOT NULL,
  `concept` VARCHAR(45) NOT NULL,
  `amount` FLOAT NOT NULL,
  `new_balance` FLOAT NOT NULL,
  `date` DATE NOT NULL,
  PRIMARY KEY (`idMOVEMENT`),
  INDEX `fk_MOVEMENT_1_idx` (`idACCOUNT` ASC),
  INDEX `fk_MOVEMENT_2_idx` (`idACCOUNT_receptor` ASC),
  CONSTRAINT `fk_MOVEMENT_1`
    FOREIGN KEY (`idACCOUNT`)
    REFERENCES `4BankDB`.`ACCOUNT` (`idACCOUNT`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_MOVEMENT_2`
    FOREIGN KEY (`idACCOUNT_receptor`)
    REFERENCES `4BankDB`.`ACCOUNT` (`idACCOUNT`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
