-- MySQL Script generated by MySQL Workbench
-- mar 10 abr 2018 18:04:11 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema 4BankDB
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `4BankDB` ;

-- -----------------------------------------------------
-- Schema 4BankDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `4BankDB` DEFAULT CHARACTER SET utf8 ;
USE `4BankDB` ;

-- -----------------------------------------------------
-- Table `4BankDB`.`USERS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `4BankDB`.`USERS` ;

CREATE TABLE IF NOT EXISTS `4BankDB`.`USERS` (
  `idUSERS` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `passsword` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `address` VARCHAR(70) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `NIF` VARCHAR(45) NOT NULL,
  `phone_number` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUSERS`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `NIF_UNIQUE` (`NIF` ASC),
  UNIQUE INDEX `phone_number_UNIQUE` (`phone_number` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `4BankDB`.`EMPLOYEE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `4BankDB`.`EMPLOYEE` ;

CREATE TABLE IF NOT EXISTS `4BankDB`.`EMPLOYEE` (
  `idUSERS` INT NOT NULL,
  `isEmployee` TINYINT(1) NOT NULL,
  INDEX `fk_EMPLOYEE_1_idx` (`idUSERS` ASC),
  CONSTRAINT `fk_EMPLOYEE_1`
    FOREIGN KEY (`idUSERS`)
    REFERENCES `4BankDB`.`USERS` (`idUSERS`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `4BankDB`.`ACCOUNT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `4BankDB`.`ACCOUNT` ;

CREATE TABLE IF NOT EXISTS `4BankDB`.`ACCOUNT` (
  `idACCOUNT` INT NOT NULL,
  `idUSERS` INT NOT NULL,
  `balance` FLOAT NULL,
  PRIMARY KEY (`idACCOUNT`, `idUSERS`),
  INDEX `fk_ACCOUNT_1_idx` (`idUSERS` ASC),
  CONSTRAINT `fk_ACCOUNT_1`
    FOREIGN KEY (`idUSERS`)
    REFERENCES `4BankDB`.`USERS` (`idUSERS`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `4BankDB`.`MOVEMENTS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `4BankDB`.`MOVEMENTS` ;

CREATE TABLE IF NOT EXISTS `4BankDB`.`MOVEMENTS` (
  `idMOVEMENTS` INT NOT NULL AUTO_INCREMENT,
  `idUSERS` INT NOT NULL,
  `idACCOUNT` INT NOT NULL,
  `idUSERS_receptor` INT NULL,
  `concept` VARCHAR(15) NOT NULL,
  `amount` FLOAT NOT NULL DEFAULT 0,
  `new_balance` FLOAT NOT NULL,
  PRIMARY KEY (`idMOVEMENTS`),
  INDEX `fk_MOVEMENTS_1_idx` (`idUSERS` ASC, `idACCOUNT` ASC),
  CONSTRAINT `fk_MOVEMENTS_1`
    FOREIGN KEY (`idUSERS` , `idACCOUNT`)
    REFERENCES `4BankDB`.`ACCOUNT` (`idUSERS` , `idACCOUNT`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_MOVEMENTS_2`
    FOREIGN KEY (`idUSERS`)
    REFERENCES `4BankDB`.`USERS` (`idUSERS`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
