version: '2'
services:
  mariadb:
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_USER=user
volumes:
  mariadb_data:
    driver: local
