version: '2'
services:
  mysql-server:
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_USER=4Bank
      - MYSQL_PASSWORD=4Bank
      - MYSQL_DATABASE=4BankDB
volumes:
  mysql_data:
    driver: local
